NPFT_Project1/force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>Appointment-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

finalproject/force-app/main/default/objects/Appointment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments2</relationshipLabel>
    <relationshipName>Appointments2</relationshipName>
    <type>Lookup</type>
</CustomField>

NPFT_Project1/force-app/main/default/objects/Appointment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Doctor)</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>End Time of the Appointment</description>
    <formula>Start_Time__c + 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Residence__c.field-meta.xml
<CustomField>
    <fullName>Residence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The location where this appointment is happening.</description>
    <label>Residence</label>
    <referenceTo>Residence__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Time and Date of the Appointment</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexes</valueSetName>
    </valueSet>
</CustomField>

finalproject/force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <description>Record type showing all custom doctor fields.</description>
    <label>Doctor</label>
</RecordType>

NPFT_Project1/force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NPFT_Project1/force-app/main/default/objects/Customer__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

NPFT_Project1/force-app/main/default/objects/Customer__c/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <formula>First_Name__c +  &quot; &quot; +  Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

NPFT_Project1/force-app/main/default/objects/Customer__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

NPFT_Project1/force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <displayFormat>DOC-{0000}</displayFormat>
        <label>Doctor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Doctors</relationshipLabel>
    <relationshipName>Doctors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Doctors</relationshipLabel>
    <relationshipName>Doctors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/Languages_Spoken__c.field-meta.xml
<CustomField>
    <fullName>Languages_Spoken__c</fullName>
    <label>Languages Spoken</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NPFT_Project1/force-app/main/default/objects/Doctor__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allergist</fullName>
            </value>
            <value>
                <fullName>Cardiologist</fullName>
            </value>
            <value>
                <fullName>Dermatologist</fullName>
            </value>
            <value>
                <fullName>Family Medicine</fullName>
            </value>
            <value>
                <fullName>Neurosurgeon</fullName>
            </value>
            <value>
                <fullName>OBGYN</fullName>
            </value>
            <value>
                <fullName>Oncologist</fullName>
            </value>
            <value>
                <fullName>Orthopedic Specialist</fullName>
            </value>
            <value>
                <fullName>Orthopedic Surgeon</fullName>
            </value>
            <value>
                <fullName>Pediatrician</fullName>
            </value>
            <value>
                <fullName>Plastic Surgeon</fullName>
            </value>
            <value>
                <fullName>Radiologist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NPFT_Project1/force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Office_Location__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

babbageprod/force-app/main/default/objects/Office_Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Office_Location__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Residence__c/Residence__c.object-meta.xml
<CustomObject>
    <label>Residence</label>
    <nameField>
        <displayFormat>Resident-{0000}</displayFormat>
        <label>Office Location Doctor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

finalproject/force-app/main/default/objects/Residence__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

finalproject/force-app/main/default/objects/Residence__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

NPFT_Project1/force-app/main/default/objects/Residence__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Residences</relationshipLabel>
    <relationshipName>Residences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/objects/Residence__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Residences</relationshipLabel>
    <relationshipName>Residences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

finalproject/force-app/main/default/objects/Residence__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

babbageprod/force-app/main/default/globalValueSets/Sexes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <masterLabel>Sexes</masterLabel>
</GlobalValueSet>

NPFT_Project1/force-app/main/default/classes/createNPFTTestData.cls
public class createNPFTTestData {
    public static void insertTestData(){
        // insert customers
        List<Customer__c> testCustomers = new List<Customer__c>();
        testCustomers.add(new Customer__c(First_Name__c='Tom', Last_Name__c='Hanks', Age__c=57, 
                                          City__c='Herndon', Country__c='USA', Sex__c='Male', State__c='VA', 
                                          Street_Address__c='357 People Road', Zip_Postal_Code__c='20170'));
        testCustomers.add(new Customer__c(Age__c = 31, City__c='Reston', Country__c='USA', 
                                          First_Name__c= 'Harvey', Last_Name__c='Hill', Sex__c='Male',
                                          State__c= 'VA', Street_Address__c='11730 American Plaza Blvd',
                                          Zip_Postal_Code__c='20170'));
        testCustomers.add(new Customer__c(Age__c=26, City__c='Herndon', Country__c='US', 
                                          First_Name__c='John', Last_Name__c='Big', Sex__c='Male', 
                                          State__c='VA', Street_Address__c='2282 Austoria Drive',
                                          Zip_Postal_Code__c='20170'));
        insert testCustomers;

        // insert account
        Account doctorAccount = new Account(Name='Doctor');
        upsert doctorAccount;

        // grab account
        doctorAccount = [SELECT Id FROM Account WHERE Name='Doctor' LIMIT 1];

        // insert contacts for each doctor
        List<Contact> testContacts = new List<Contact>();
        testContacts.add(new Contact(FirstName='Ben', LastName='Learn', AccountId=doctorAccount.Id));
        testContacts.add(new Contact(FirstName='Francesco', LastName='Ward', AccountId=doctorAccount.Id));
        testContacts.add(new Contact(FirstName='Simon', LastName='Jose', AccountId=doctorAccount.Id));
        testContacts.add(new Contact(FirstName='Bailey', LastName='Dawkins', AccountId=doctorAccount.Id));
        testContacts.add(new Contact(FirstName='Jonathan', LastName='Liu', AccountId=doctorAccount.Id));
        testContacts.add(new Contact(FirstName='Emily', LastName='Blunt', AccountId=doctorAccount.Id));

        insert testContacts;

        // temp contact to create lookup relationship
        Contact tempContact;
        String fullName;

        // insert doctors
        List<Doctor__c> testDoctors = new List<Doctor__c>();

        fullName = 'Ben Learn';
        tempContact = [SELECT Id FROM Contact WHERE Name=:fullName LIMIT 1];
        testDoctors.add(new Doctor__c(First_Name__c='Ben', Last_Name__c='Learn', Email__c='blearn@gmail.com', 
                                        Languages_Spoken__c='Chinese', Phone_Number__c='8654125796', Sex__c='Male', 
                                        Specialty__c='Neurosurgeon', Account__c=doctorAccount.Id, Contact__c=tempContact.Id));

        fullName = 'Francesco Ward';
        tempContact = [SELECT Id FROM Contact WHERE Name=:fullName LIMIT 1];
        testDoctors.add(new Doctor__c(First_Name__c='Francesco', Last_Name__c='Ward', Email__c='fward@gmail.com', 
                                        Languages_Spoken__c= 'English;Chinese', Phone_Number__c='987532587',
                                        Sex__c='Male', Specialty__c='Plastic Surgeon', Account__c=doctorAccount.Id, 
                                        Contact__c=tempContact.Id));
        
        fullName = 'Simon Jose';
        tempContact = [SELECT Id FROM Contact WHERE Name=:fullName LIMIT 1];
        testDoctors.add(new Doctor__c(First_Name__c='Simon', Last_Name__c='Jose', Email__c='sjose@gmail.com', 
                                        Languages_Spoken__c='English;Spanish;Chinese', Phone_Number__c='8527531598',
                                        Sex__c='Male', Specialty__c='Family Medicine', Account__c=doctorAccount.Id, 
                                        Contact__c=tempContact.Id));
        
        fullName = 'Bailey Dawkins';
        tempContact = [SELECT Id FROM Contact WHERE Name=:fullName LIMIT 1];
        testDoctors.add(new Doctor__c(First_Name__c='Bailey', Last_Name__c='Dawkins', Email__c='bdawkins@gmail.com', 
                                        Languages_Spoken__c='English;Spanish', Phone_Number__c='5548659657',
                                        Sex__c='Male', Specialty__c='Cardiologist', Account__c=doctorAccount.Id, 
                                        Contact__c=tempContact.Id));

        fullName = 'Jonathan Liu';
        tempContact = [SELECT Id FROM Contact WHERE Name=:fullName LIMIT 1];
        testDoctors.add(new Doctor__c(First_Name__c='Jonathan', Last_Name__c='Liu', Email__c='jliu@gmail.com', 
                                        Languages_Spoken__c='English', Phone_Number__c='4125879654',
                                        Sex__c='Male', Specialty__c='Allergist', Account__c=doctorAccount.Id, 
                                        Contact__c=tempContact.Id));

        fullName = 'Emily Blunt';
        tempContact = [SELECT Id FROM Contact WHERE Name=:fullName LIMIT 1];
        testDoctors.add(new Doctor__c(First_Name__c='Emily', Last_Name__c='Blunt', Email__c='eblunt@gmail.com', 
                                        Languages_Spoken__c='English', Phone_Number__c='8569874523',
                                        Sex__c='Female', Specialty__c='Orthopedic Specialist', Account__c=doctorAccount.Id,
                                        Contact__c=tempContact.Id));
        insert testDoctors;


        // insert office locations
        List<Office_Location__c> testOffices = new List<Office_Location__c>();
        testOffices.add(new Office_Location__c(City__c='North Hollywood', Country__c='USA', Name='Sacred Heart', State__c='VA',
                                                Street_Address__c='12629 Riverside Drive', Zip_Postal_Code__c='20170'));
        testOffices.add(new Office_Location__c(City__c='Reston', Country__c='USA', Name='Revature Office', State__c='VA',
                                                Street_Address__c='11730 Plaza America Blvd', Zip_Postal_Code__c='20170'));
        testOffices.add(new Office_Location__c(City__c='Arlington', Country__c='US', Name='Virginia Hospital Center', 
                                                State__c='VA', Street_Address__c='1701 N George Mason Drive', 
                                                Zip_Postal_Code__c='20170'));
        insert testOffices;

        // insert appointments
        List<Appointment__c> testAppointments = new List<Appointment__c>();
        Doctor__c tempDoctor;
        Customer__c tempCustomer;

        tempDoctor = [SELECT Id FROM Doctor__c WHERE First_Name__c='Ben' AND Last_Name__c='Learn' LIMIT 1];
        tempCustomer = [SELECT Id FROM Customer__c WHERE FullName__c='John Big' LIMIT 1];
        testAppointments.add(new Appointment__c(Doctor__c=tempDoctor.Id, Customer__c=tempCustomer.Id, 
                                                Start_Time__c=DateTime.newInstance(2019, 11, 28, 13, 0, 0), 
                                                End_Time__c=DateTime.newInstance(2019, 11, 28, 14, 0, 0)));

        tempDoctor = [SELECT Id FROM Doctor__c WHERE First_Name__c='Bailey' AND Last_Name__c='Dawkins' LIMIT 1];
        tempCustomer = [SELECT Id FROM Customer__c WHERE FullName__c='Harvey Hill' LIMIT 1];
        testAppointments.add(new Appointment__c(Doctor__c=tempDoctor.Id, Customer__c=tempCustomer.Id, 
                                                Start_Time__c=DateTime.newInstance(2019, 11, 29, 10, 0, 0), 
                                                End_Time__c=DateTime.newInstance(2019, 11, 29, 11, 0, 0)));
        
        tempDoctor = [SELECT Id FROM Doctor__c WHERE First_Name__c='Simon' AND Last_Name__c='Jose' LIMIT 1];
        tempCustomer = [SELECT Id FROM Customer__c WHERE FullName__c='Tom Hanks' LIMIT 1];
        testAppointments.add(new Appointment__c(Doctor__c=tempDoctor.Id, Customer__c=tempCustomer.Id, 
                                                Start_Time__c=DateTime.newInstance(2019, 11, 26, 16, 0, 0), 
                                                End_Time__c=DateTime.newInstance(2019, 11, 26, 17, 0, 0)));

        tempDoctor = [SELECT Id FROM Doctor__c WHERE First_Name__c='Francesco' AND Last_Name__c='Ward' LIMIT 1];
        tempCustomer = [SELECT Id FROM Customer__c WHERE FullName__c='Tom Hanks' LIMIT 1];
        testAppointments.add(new Appointment__c(Doctor__c=tempDoctor.Id, Customer__c=tempCustomer.Id, 
                                                Start_Time__c=DateTime.newInstance(2019, 11, 20, 12, 0, 0), 
                                                End_Time__c=DateTime.newInstance(2019, 11, 20, 13, 0, 0)));

        insert testAppointments;

        // insert residences
        List<Residence__c> testResidences = new List<Residence__c>();
        Office_Location__c sh = [SELECT Id FROM Office_Location__c WHERE Name='Sacred Heart' LIMIT 1];
        Office_Location__c ro = [SELECT Id FROM Office_Location__c WHERE Name='Revature Office' LIMIT 1];
        Office_Location__c vhc = [SELECT Id FROM Office_Location__c WHERE Name='Virginia Hospital Center' LIMIT 1];

        tempDoctor = [SELECT Id FROM Doctor__c WHERE First_Name__c='Ben' AND Last_Name__c='Learn' LIMIT 1];
        testResidences.add(new Residence__c(Doctor__c=tempDoctor.Id, Office_Location__c=sh.id));
        testResidences.add(new Residence__c(Doctor__c=tempDoctor.Id, Office_Location__c=ro.id));

        tempDoctor = [SELECT Id FROM Doctor__c WHERE First_Name__c='Simon' AND Last_Name__c='Jose' LIMIT 1];
        testResidences.add(new Residence__c(Doctor__c=tempDoctor.Id, Office_Location__c=sh.id));
        testResidences.add(new Residence__c(Doctor__c=tempDoctor.Id, Office_Location__c=ro.id));
        testResidences.add(new Residence__c(Doctor__c=tempDoctor.Id, Office_Location__c=vhc.id));

        tempDoctor = [SELECT Id FROM Doctor__c WHERE First_Name__c='Bailey' AND Last_Name__c='Dawkins' LIMIT 1];
        testResidences.add(new Residence__c(Doctor__c=tempDoctor.Id, Office_Location__c=ro.id));
        testResidences.add(new Residence__c(Doctor__c=tempDoctor.Id, Office_Location__c=vhc.id));
        testResidences.add(new Residence__c(Doctor__c=tempDoctor.Id, Office_Location__c=sh.id));

        tempDoctor = [SELECT Id FROM Doctor__c WHERE First_Name__c='Francesco' AND Last_Name__c='Ward' LIMIT 1];
        testResidences.add(new Residence__c(Doctor__c=tempDoctor.Id, Office_Location__c=ro.id));
        testResidences.add(new Residence__c(Doctor__c=tempDoctor.Id, Office_Location__c=sh.id));

        tempDoctor = [SELECT Id FROM Doctor__c WHERE First_Name__c='Emily' AND Last_Name__c='Blunt' LIMIT 1];
        testResidences.add(new Residence__c(Doctor__c=tempDoctor.Id, Office_Location__c=vhc.id));
        
        tempDoctor = [SELECT Id FROM Doctor__c WHERE First_Name__c='Jonathan' AND Last_Name__c='Liu' LIMIT 1];
        testResidences.add(new Residence__c(Doctor__c=tempDoctor.Id, Office_Location__c=vhc.id));
        
        insert testResidences;
    }

    public static void clearTestData(){
        // delete appointments and residences
        List<Appointment__c> testAppointments = [SELECT Id FROM Appointment__c];
        delete testAppointments;
        List<Residence__c> testResidences = [SELECT Id FROM Residence__c];
        delete testResidences;

        // delete customers and office locations
        List<Customer__c> testCustomers = [SELECT Id FROM Customer__c];
        delete testCustomers;
        List<Office_Location__c> testOffices = [SELECT Id FROM Office_Location__c];
        delete testOffices;

        // delete doctor account and doctors
        List<Doctor__c> testDoctors = [SELECT Id FROM Doctor__c];
        delete testDoctors;
    }
}