NPFT_Project1/force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>Appointment-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

NPFT_Project1/force-app/main/default/objects/Appointment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Doctor)</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Residence__c.Doctor__c</field>
            <operation>equals</operation>
            <valueField>$Source.Doctor__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Residence__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Residence__c.field-meta.xml
<CustomField>
    <fullName>Residence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The location where this appointment is happening.</description>
    <label>Residence</label>
    <referenceTo>Residence__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Time and Date of the Appointment</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unconfirmed</fullName>
                <default>true</default>
                <label>Unconfirmed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexes</valueSetName>
    </valueSet>
</CustomField>

finalproject/force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <description>Record type showing all custom doctor fields.</description>
    <label>Doctor</label>
</RecordType>

NPFT_Project1/force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Full_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_Address__c</fullName>
    <formula>Street_Address__c + City__c +  State__c +  Country__c +  Zip_Postal_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

NPFT_Project1/force-app/main/default/objects/Customer__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

NPFT_Project1/force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <displayFormat>DOC-{0000}</displayFormat>
        <label>Doctor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/Languages_Spoken__c.field-meta.xml
<CustomField>
    <fullName>Languages_Spoken__c</fullName>
    <label>Languages Spoken</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NPFT_Project1/force-app/main/default/objects/Doctor__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allergist</fullName>
            </value>
            <value>
                <fullName>Cardiologist</fullName>
            </value>
            <value>
                <fullName>Dermatologist</fullName>
            </value>
            <value>
                <fullName>Family Medicine</fullName>
            </value>
            <value>
                <fullName>Neurosurgeon</fullName>
            </value>
            <value>
                <fullName>OBGYN</fullName>
            </value>
            <value>
                <fullName>Oncologist</fullName>
            </value>
            <value>
                <fullName>Orthopedic Specialist</fullName>
            </value>
            <value>
                <fullName>Orthopedic Surgeon</fullName>
            </value>
            <value>
                <fullName>Pediatrician</fullName>
            </value>
            <value>
                <fullName>Plastic Surgeon</fullName>
            </value>
            <value>
                <fullName>Radiologist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NPFT_Project1/force-app/main/default/objects/Doctor__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Doctors</relationshipName>
    <type>Lookup</type>
</CustomField>

NPFT_Project1/force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NPFT_Project1/force-app/main/default/objects/Office_Location__c/fields/Full_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_Address__c</fullName>
    <formula>Street_Address__c +  City__c +  State__c  + Country__c +  Zip_Postal_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Residence__c/Residence__c.object-meta.xml
<CustomObject>
    <label>Residence</label>
    <nameField>
        <displayFormat>Resident-{0000}</displayFormat>
        <label>Office Location Doctor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Residence</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

NPFT_Project1/force-app/main/default/objects/Residence__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Residences</relationshipLabel>
    <relationshipName>Residences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

finalproject/force-app/main/default/objects/Residence__c/fields/Full_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_Address__c</fullName>
    <formula>Street_Address__c &amp; &quot; &quot; &amp; City__c &amp; &quot; &quot; &amp; State__c &amp; &quot; &quot; &amp; Country__c &amp; &quot; &quot; &amp; TEXT( Postal_Code__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

babbageprod/force-app/main/default/objects/Residence__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Residences</relationshipLabel>
    <relationshipName>Residences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/globalValueSets/Sexes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <masterLabel>Sexes</masterLabel>
</GlobalValueSet>

NPFT_Project1/force-app/main/default/classes/CustomerPageController.cls
public without sharing class CustomerPageController {
    public List<Doctor__c> doctorList{get;set;}

    public List<SelectOption> doctorAppointmentPicker{get; set;}

    public List<SelectOption> specialtyList{get
    {
        List<SelectOption> specialtyOptions=new List<SelectOption>();
        List<Schema.PicklistEntry> specialtyPicklist = Doctor__c.specialty__c.getDescribe().getPickListValues();
        for (Schema.PicklistEntry entry : specialtyPicklist)
        {
            specialtyOptions.add(new SelectOption(entry.getValue(),entry.getLabel()));
        }
        return specialtyOptions;
    }}
    public List<SelectOption> languagesList{get
    {
        List<SelectOption> languagesOptions=new List<SelectOption>();
        List<Schema.PicklistEntry> languagesPicklist = Doctor__c.languages_spoken__c.getDescribe().getPickListValues();
        for(Schema.PicklistEntry entry: languagesPicklist)
        {
            languagesOptions.add(new SelectOption(entry.getValue(),entry.getLabel()));
        }
        return languagesOptions;
    }}
    public List<SelectOption> sexList{get
    {
        List<SelectOption> sexOptions=new List<SelectOption>();
        List<Schema.PicklistEntry> sexPickList = Doctor__c.sex__c.getDescribe().getPickListValues();
        for(Schema.PicklistEntry entry: sexPickList)
        {
            sexOptions.add(new SelectOption(entry.getValue(),entry.getLabel()));
        }
        return sexOptions;
    }}


    public string sexPref{get;set;}
    public string specialtyPref{get;set;}
    public string languagesPref{get;set;}
    public DateTime appointmentStartTime{get;set;}
    public string appointmentDescription{get;set;}
    public string appointmentDoctor{get;set;}
    public string outputMessage{get;set;}
    public CustomerPageController() {
        doctorAppointmentPicker = new List<SelectOption>();

    }

    public void updateList()
    {
        string queryString='SELECT first_name__c, last_name__c , sex__c, specialty__c, Languages_Spoken__c, email__c FROM Doctor__c';
        boolean multiFilter=false;
        if(sexPref!=null || specialtyPref!=null || languagesPref.length()>2)
            queryString=queryString+' WHERE';
        if(sexPref!=null){
            queryString=queryString+' sex__c=\''+sexPref+'\'';
            multifilter=true;
        }
        if(specialtyPref!=null){
            if(multifilter==true)
                queryString=queryString+ ' AND';
            queryString=queryString+' specialty__c=\''+specialtyPref+'\'';
            multifilter=true;
        }
        if(languagesPref.length()>2){
            if(multifilter==true)
                queryString=queryString+ ' AND';
            languagesPref=languagesPref.substring(1,languagesPref.length()-1); //gets ride of brackets
            languagesPref=languagesPref.replace(', ',';');
            queryString=queryString+' Languages_Spoken__c includes(\''+languagesPref+'\')';
            multifilter=true;
        }
        doctorList=Database.query(queryString);
       

        doctorAppointmentPicker.clear();
        for(Doctor__c doc : doctorList)
        {
            List<Residence__c> residenceList=[Select office_location__r.id, office_location__r.Full_Address__c FROM Residence__C Where Doctor__r.id = :doc.id];
            for(Residence__c residence:residenceList)
                doctorAppointmentPicker.add(new SelectOption(doc.Id+' '+residence.id, doc.first_name__c + ' '+doc.last_name__c+' '+residence.office_location__r.Full_Address__c));
        }       
    }
    public void scheduleAppointment(){
        if(appointmentStartTime==null){
            outputMessage='Please select an appointment time';
            return;
        }
        else if (appointmentDoctor==null){
            outputMessage='Please select a doctor. If there are no doctors in the list, search for one first';
        }
        appointment__c newAppointment=new appointment__C();
        List<customer__c> customerList=[SELECT id FROM Customer__c where user__C=:UserInfo.getUserId()];
        if(customerList.size()>0)
            newAppointment.customer__c=customerList.get(0).id;
        newAppointment.Description__c=appointmentDescription;
        newAppointment.Doctor__c=appointmentDoctor.split(' ')[0];
        newAppointment.start_time__c=appointmentStartTime;
        newAppointment.location__c=appointmentDoctor.split(' ')[1];
        newAppointment.Status__c='Pending';
        try{
            insert newAppointment;
        }
        catch(exception e){
            outputMessage='Server error: Could not schedule appointment. Error:'+e.getMessage();
        }
    }

    

}