force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NPFT_Project1/force-app/main/default/objects/Customer__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <formula>First_Name__c +  Middle_Initial__c +  Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

NPFT_Project1/force-app/main/default/objects/Customer__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/createNPFTTestData.cls
public class createNPFTTestData {
    public static void insertTestData(){
        List<Customer__c> testCustomers = new List<Customer__c>();
        testCustomers.add(new Customer__c(First_Name__c='Tom', Last_Name__c='Hanks', Age__c=57, 
                                          City__c='Herndon', Country__c='USA', Sex__c='Male', State__c='VA', 
                                          Street_Address__c='357 People Road', Zip_Postal_Code__c='20170'));
        insert testCustomers;

        Customer__c td = [SELECT Id, FullName__c FROM Customer__c WHERE First_Name__c='Tom' LIMIT 1];
        System.debug(td.FullName__c);
    }
}