babbageprod/force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APPT-{00000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Doctor)</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Residence__c.field-meta.xml
<CustomField>
    <fullName>Residence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Residence</label>
    <referenceTo>Residence__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Time and Date of the Appointment</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/fields/Flagged__c.field-meta.xml
<CustomField>
    <fullName>Flagged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flagged</label>
    <type>Checkbox</type>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

babbageprod/force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <label>Doctor</label>
</RecordType>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Residence__c/Residence__c.object-meta.xml
<CustomObject>
    <label>Residence</label>
    <nameField>
        <label>Residence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Residence__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Residences</relationshipLabel>
    <relationshipName>Residences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/objects/Residence__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Residences</relationshipLabel>
    <relationshipName>Residences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/classes/TestFlagDoctors.cls
/* Hey, why is the entirety of this class commmented out?
 * 
 * Well that's because it inserts appointment records with start times in the past in order to test our
 * UpdateCompletedAppointments apex class, but a validation rule that we set on the Appointment__c object
 * prevents just this thing. So the test method in this class will ALWAYS FAIL unless you temporarily turn off
 * the validation rule to complete the test and uncomment the code below. 
 * 
 * MAKE SURE THAT YOU IMMEDIATELY ACTIVATE THE VALIDATION RULE AGAIN AND RECOMMENT THE CODE BELOW AFTER 
 * COMPLETION!!!! */

@isTest
public class TestFlagDoctors {
    // Dummy CRON expression: midnight on March 15.
    // Because this is a test, job executes
    // immediately after Test.stopTest().
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    
    /*
    @isTest static void testFlagging(){
        // make two doctors and five customers
        DataFactory.InitalizeAccounts();
        DataFactory.CreateDoctors(2);
        DataFactory.CreateCustomers(5);
        DataFactory.CreateOfficeLocations(1);
        
        // give each doctor a residence at our office location
        Id doctorRecordTypeId = [SELECT Id FROM RecordType WHERE Name='Doctor' and sObjectType='Contact'
                                 LIMIT 1].Id;
        List<Contact> doctors = [SELECT Id FROM Contact WHERE RecordTypeId=:doctorRecordTypeId];
        Office_Location__c office = [SELECT Id FROM Office_Location__c LIMIT 1];
        List<Residence__c> doctorResidences = new List<Residence__c>();
        doctorResidences.add(new Residence__c(Doctor__c=doctors[0].Id, Office_Location__c=office.Id));
        doctorResidences.add(new Residence__c(Doctor__c=doctors[1].Id, Office_Location__c=office.Id));
        insert doctorResidences;
        
        // make a bunch of appointments
        Id customerRecordTypeId = [SELECT Id FROM RecordType WHERE Name='Customer' and sObjectType='Contact'
                                   LIMIT 1].Id;
        List<Contact> customers = [SELECT Id FROM Contact WHERE RecordTypeId=:customerRecordTypeId];
        List<Appointment__c> testAppointments = new List<Appointment__c>();
        for(Integer i = 0; i < 5; i++){
            testAppointments.add(new Appointment__c(Start_Time__c=DateTime.now().addMonths(-2), 
                                                    Customer__c=customers[i].Id, Doctor__c=doctors[0].Id,
                                                    Residence__c=doctorResidences[0].Id));
            testAppointments.add(new Appointment__c(Start_Time__c=DateTime.now().addMonths(-3), 
                                                    Customer__c=customers[i].Id, Doctor__c=doctors[0].Id,
                                                    Residence__c=doctorResidences[0].Id));
        }
        for(Integer i = 0; i < 5; i++){
            testAppointments.add(new Appointment__c(Start_Time__c=DateTime.now().addMonths(-2), 
                                                    Customer__c=customers[i].Id, Doctor__c=doctors[1].Id,
                                                    Residence__c=doctorResidences[1].Id));
        }
        insert testAppointments;
        
        Test.startTest();
        String jobId = System.schedule('ScheduledApexTest', CRON_EXP, new FlagDoctors());
        Test.stopTest();
        
        List<Contact> badDoctors = [SELECT Id FROM Contact WHERE Flagged__c=true];
        System.assertEquals(1, badDoctors.size());
    }*/
}