babbageprod/force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APPT-{00000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Doctor)</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Doctor_Message__c.field-meta.xml
<CustomField>
    <fullName>Doctor_Message__c</fullName>
    <label>Doctor Message</label>
    <type>TextArea</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <formula>Start_Time__c + (1/24)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Residence__c.field-meta.xml
<CustomField>
    <fullName>Residence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Residence</label>
    <referenceTo>Residence__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Time and Date of the Appointment</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Residence__c/Residence__c.object-meta.xml
<CustomObject>
    <label>Residence</label>
    <nameField>
        <label>Residence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Residence__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Residences</relationshipLabel>
    <relationshipName>Residences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

finalproject/force-app/main/default/objects/Residence__c/fields/Full_Address__c.field-meta.xml
<CustomField>
    <fullName>Full_Address__c</fullName>
    <formula>Street_Address__c &amp; &quot; &quot; &amp; City__c &amp; &quot; &quot; &amp; State__c &amp; &quot; &quot; &amp; Country__c &amp; &quot; &quot; &amp; TEXT( Postal_Code__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Address</label>
    <type>Text</type>
</CustomField>

babbageprod/force-app/main/default/objects/Residence__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Residences</relationshipLabel>
    <relationshipName>Residences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/classes/CustomerAppointmentController.cls
//This Controller will Query the information in the custom Object:
//Appointment__c; The Status__c
public class CustomerAppointmentController {
    
    @AuraEnabled
    public static List<Appointment__c> getAppointmentConfirmed(){
        List<Appointment__c> appointments = [SELECT Name, Doctor__r.Name, Residence__r.Office_Location__r.Name, Residence__r.Office_Location__r.Full_Address__c, Start_Time__c, End_Time__c, Status__c, 
                                             Doctor_Message__c FROM Appointment__c WHERE Status__c = 'Confirmed'];
        
        return appointments;
    }
    
    @AuraEnabled
    public static List<Appointment__c> getAppointmentPending(){
        List<Appointment__c> appointments = [SELECT Name, Doctor__r.Name, Residence__r.Office_Location__r.Name, Residence__r.Office_Location__r.Full_Address__c, Start_Time__c, End_Time__c, Status__c, 
                                             Doctor_Message__c FROM Appointment__c WHERE Status__c = 'Pending'];
        
        return appointments;
    }
    
    @AuraEnabled
    public static List<Appointment__c> getAppointmentRescheduled(){
        List<Appointment__c> appointments = [SELECT Name, Doctor__r.Name, Residence__r.Office_Location__r.Name, Residence__r.Office_Location__r.Full_Address__c, Start_Time__c, End_Time__c, Status__c, 
                                             Doctor_Message__c FROM Appointment__c WHERE Status__c = 'Rescheduled'];
        
        return appointments;
    }
    
    @AuraEnabled
    public static List<Appointment__c> getAppointmentRejected(){
        List<Appointment__c> appointments = [SELECT Name, Doctor__r.Name, Residence__r.Office_Location__r.Name, Residence__r.Office_Location__r.Full_Address__c, Start_Time__c, End_Time__c, Status__c, 
                                             Doctor_Message__c FROM Appointment__c WHERE Status__c = 'Rejected'];

        return appointments;
    }
}