babbageprod/force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APPT-{00000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Doctor)</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Doctor_Message__c.field-meta.xml
<CustomField>
    <fullName>Doctor_Message__c</fullName>
    <label>Doctor Message</label>
    <type>TextArea</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <formula>Start_Time__c + (1/24)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Residence__c.field-meta.xml
<CustomField>
    <fullName>Residence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Residence</label>
    <referenceTo>Residence__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Time and Date of the Appointment</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Residence__c/Residence__c.object-meta.xml
<CustomObject>
    <label>Residence</label>
    <nameField>
        <label>Residence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Residence__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Residences</relationshipLabel>
    <relationshipName>Residences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/objects/Residence__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Residences</relationshipLabel>
    <relationshipName>Residences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/globalValueSets/Languages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>English</fullName>
        <default>true</default>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <masterLabel>Languages</masterLabel>
</GlobalValueSet>

babbageprod/force-app/main/default/classes/DoctorAppointmentController.cls
global class DoctorAppointmentController {
    @auraEnabled
    global static List<Appointment__c[]> getAppointmentsByDay(DateTime startDay, Datetime endDay){
        List<Appointment__c[]> appointments = new List<Appointment__C[]>();
        ID UserID= [SELECT ContactID FROM User WHERE id=:UserInfo.getuserID()][0].ContactId;
        for(integer i=1;i<=7;i++)
            appointments.add([SELECT customer__r.Name, customer__r.email, Start_time__c, Description__c, Language_Preference__c, residence__r.office_location__r.Name FROM Appointment__c WHERE Doctor__c=:UserID AND DAY_IN_WEEK(Start_time__c)=:i AND Start_time__c>=:startDay AND Start_Time__C<=:EndDay ORDER BY Start_time__c]);
        return appointments;
    }
    @auraEnabled
    global static String[] getAppointmentStatusValues(){
        String[] filterList=new String[]{'All'};
            List<Schema.PickListEntry> picklistEntries=appointment__c.status__c.getDescribe().getPickListValues();
        for (integer i=0;i<picklistEntries.size();i++)
        {
            filterList.add(picklistEntries[i].getValue());
        }
        return filterList;
    }
    @auraEnabled
    global static List<Appointment__c> getAppointmentsByStatus(String Status, String TimeFrame, String Period)
    {	
        System.debug(Status+TimeFrame+Period);
                ID UserID= [SELECT ContactID FROM User WHERE id=:UserInfo.getuserID()][0].ContactId;
        string query='SELECT customer__r.Name, start_time__c, end_time__c, description__c, language_preference__c, status__c,'+ 
            'customer__r.Phone, customer__r.Email, doctor_message__c, Residence__r.office_location__r.Name FROM Appointment__c';
        if(TimeFrame=='Past') {
            if(Period!='All')
                query=query+' WHERE end_time__c<TODAY AND start_time__c=LAST_N_DAYS:'+Period;
            else
                query=query+' WHERE end_time__c<TODAY';
        }
        else {
            if(Period!='All')
                query=query+' WHERE end_time__c=NEXT_N_DAYS:'+Period;
            else
                query=query+' WHERE end_time__c>TODAY';
        }
        if(Status!='All')
            query=query+' AND status__c=\''+status+'\'';
        query=query+' AND Doctor__c=\''+UserID+'\'';
        return Database.query(query);
    }
    @auraEnabled
    global static void updateAppointment(Appointment__c appointment){
        update appointment;
    }
}