babbageprod/force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APPT-{00000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

finalproject/force-app/main/default/objects/Appointment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments2</relationshipLabel>
    <relationshipName>Appointments2</relationshipName>
    <type>Lookup</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Doctor)</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Doctor_Message__c.field-meta.xml
<CustomField>
    <fullName>Doctor_Message__c</fullName>
    <label>Doctor Message</label>
    <type>TextArea</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Residence__c.field-meta.xml
<CustomField>
    <fullName>Residence__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Residence</label>
    <referenceTo>Residence__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Time and Date of the Appointment</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/fields/Conditions__c.field-meta.xml
<CustomField>
    <fullName>Conditions__c</fullName>
    <label>Conditions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Breast Cancer</fullName>
            </value>
            <value>
                <fullName>Skin Cancer</fullName>
            </value>
            <value>
                <fullName>Lung Cancer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexes</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Specialties</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

babbageprod/force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <label>Doctor</label>
</RecordType>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NPFT_Project1/force-app/main/default/objects/Customer__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Doctors</relationshipLabel>
    <relationshipName>Doctors</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Office_Location__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

babbageprod/force-app/main/default/objects/Office_Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

babbageprod/force-app/main/default/objects/Office_Location__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

babbageprod/force-app/main/default/objects/Office_Location__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

babbageprod/force-app/main/default/objects/Residence__c/Residence__c.object-meta.xml
<CustomObject>
    <label>Residence</label>
    <nameField>
        <label>Residence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

finalproject/force-app/main/default/objects/Residence__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

babbageprod/force-app/main/default/objects/Residence__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Residences</relationshipLabel>
    <relationshipName>Residences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/objects/Residence__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Residences</relationshipLabel>
    <relationshipName>Residences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

finalproject/force-app/main/default/objects/Residence__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

babbageprod/force-app/main/default/objects/Search__c/Search__c.object-meta.xml
<CustomObject>
    <label>Search</label>
    <nameField>
        <displayFormat>Search-{00000}</displayFormat>
        <label>Search Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Searches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Search__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Searches</relationshipLabel>
    <relationshipName>Searches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/objects/Search__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Search__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexes</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Search__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Specialties</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Search__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <formula>NOW()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

babbageprod/force-app/main/default/globalValueSets/Languages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>English</fullName>
        <default>true</default>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <masterLabel>Languages</masterLabel>
</GlobalValueSet>

babbageprod/force-app/main/default/globalValueSets/Sexes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <masterLabel>Sexes</masterLabel>
</GlobalValueSet>

babbageprod/force-app/main/default/globalValueSets/Specialties.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cardiologist</fullName>
    </customValue>
    <customValue>
        <fullName>Chiropractor</fullName>
    </customValue>
    <customValue>
        <fullName>General Practitioner</fullName>
    </customValue>
    <customValue>
        <fullName>Oncologist</fullName>
    </customValue>
    <customValue>
        <fullName>OBGYN</fullName>
    </customValue>
    <customValue>
        <fullName>Proctologist</fullName>
    </customValue>
    <masterLabel>Specialties</masterLabel>
</GlobalValueSet>

babbageprod/force-app/main/default/classes/DataFactory.cls
public class DataFactory{
    enum UserType {Doctor,Customer}
    static string defaultEmail='test@test.com';
    static string[] LastNameList=new List<String>{
        'Smith','Johnson','Williams',
        'Jones','Brown','Davis',
        'Miller','Wilson','Moore',
        'Taylor','Anderson','Thomas',
        'Hall','Allen','Young',
        'Hernandaz','Sanchez','Morris'
    };
    static string[] FirstNameMaleList=new List<String>{
        'James','John','Robert',
        'Michael','William','David',
        'Richard','Joseph','Thomas',
        'Charles','Christopher','Daniel'
    };
    static string[] FirstNameFemaleList=new List<String>{
        'Mary','Patricia','Jennifer',
        'Linda','Elizabeth','Barbara',
        'Susan','Jessica','Sarah',
        'Karen','Nancy','Margaret'
    };

    //includes Washington DC as DC
    static string[] StateList=new List<String>{
        'AL','AK','AZ','AR','CA',
        'CO','CT','DE','DC','FL',
        'GA','HI','ID','IL','IN',
        'IA','KS','KY','LA','ME',
        'MD','MA','MI','MN','MS',
        'MO','MT','NE','NV','NH',
        'NJ','NM','NY','NC','ND',
        'OH','OK','OR','PA','RI',
        'SC','SD','TN','TX','UT',
        'VT','VA','WA','WV','WI','WY'
    };

    static string[] StreetNameList=new List<String>{
        'Generic st',
        'Boring rd',
        'Sample st'
    };

    static string[] CityList=new List<String>{
        'GenericVille',
        'BoringTown',
        'SampleWay'
    };

    static string[] OfficeNameList=new List<String>{
        'Generic Plus',
        'Boring Central',
        'Sample Office'
    };

    static string[] DescriptionList=new List<String>{
        'Owie ouchie',
        'Oof. I\'m hurting really bad',
        'Yowch',
        'Big boo boo'
    };

    static string defaultDoctorMessage='Default Message';

    public static void CreateAll(integer n){
        InitalizeAccounts();
        CreateOfficeLocations(n);
        CreateContacts(n);
        CreateResidences(3);
        CreateAppointments(3);
        CreateSearches(6);
        CreateDoctorSurveys(3);
        CreateOfficeSurveys(3);        
    }
    public static void InitalizeAccounts(){
        if([SELECT ID FROM Account WHERE Name='Doctor Account' LIMIT 1].size()!=1)
        {
            Account newAcc = new Account();
            newAcc.Name='Doctor Account';
            insert newAcc;
        }
        if([SELECT ID FROM Account WHERE Name='Customer Account' LIMIT 1].size()!=1)
        {
            Account newAcc=new Account();
            newAcc.Name='Customer Account';
            insert newAcc;
        }
    }
    /* Use BabbageCommunityUser.cls to create Users
    public static void CreateUsers(integer n, UserType type){
        ID profileID= [SELECT ID FROM Profile WHERE Name='Babbage Customer User' LIMIT 1].ID;
        Account userAccount=[SELECT ID FROM Account WHERE name=':type.name() Account' LIMIT 1];
        if(userAccount==null)
        {
            userAccount=new Account();
            userAccount.name=type.Name()+' Account';
            insert userAccount;
        }

        List<Contact> insertList=new List<Contact>();
        for(integer i=0;i<n;i++){
            User u=new User();
            u.profileID=profileID;
            u.email=defaultEmail;
            u.LastName=LastNameList[Integer.valueof(Math.random()*LastNameList.size())];
            //u.FirstName=FirstNameMaleList[Integer.valueof(Math.random()*FirstNameMaleList.size())];
            if(type==UserType.Doctor){


            }
            else if(type==UserType.Customer){

            }
        }
    }
    */
    public static void CreateContacts(integer n){
        CreateDoctors(n);
        createCustomers(n);
    }
    public static void CreateDoctors(integer n){
        List<Contact> contactList=new List<Contact>();
        ID accountID=[SELECT ID FROM Account WHERE Name='Doctor Account' LIMIT 1].ID;
        ID recordTypeID=[SELECT ID FROM RecordType WHERE Name='Doctor' and sObjectType='Contact' LIMIT 1].ID;
        for(integer i=0;i<n;i++)
        {	
            Contact newCont=new Contact();
            newCont.RecordTypeID=recordTypeID;
            newCont.AccountID =accountID;
            newCont.email=defaultEmail;
            if (Math.Random()>=0.5){
                newCont.sex__c='Male';
                newCont.FirstName=FirstNameMaleList[Integer.valueof(Math.random()*FirstNameMaleList.size())];
                newCont.LastName=LastNameList[Integer.valueof(Math.random()*LastNameList.size())];
            }
            else{
                newCont.sex__c='Female';
                newCont.FirstName=FirstNameFemaleList[Integer.valueof(Math.random()*FirstNameFemaleList.size())];
                newCont.LastName=LastNameList[Integer.valueof(Math.random()*LastNameList.size())];
            }

            List<Schema.PickListEntry> LanguageList=Contact.language__c.getDescribe().getPicklistValues();
            newCont.language__c='';
            for(integer j=Integer.valueof(Math.floor(Math.Random()*2));j>=0;j--)
            {
                integer randNum=Integer.valueof(Math.Random()*(LanguageList.size()));
                newCont.language__c=LanguageList[randNum].getValue()+';'+newCont.language__c;
                LanguageList.remove(randNum);
            }

            List<Schema.PickListEntry> specList=Contact.specialization__c.getDescribe().getPicklistValues();
            newCont.specialization__c=specList[Integer.valueof(Math.floor(Math.random()*(specList.size())))].getValue();
            contactList.add(newCont);
        }
        insert contactList;

    }
    public static void CreateCustomers(integer n){
        List<Contact> contactList=new List<Contact>();
        ID accountID=[SELECT ID FROM Account WHERE Name='Customer Account' LIMIT 1].ID;
        ID recordTypeID=[SELECT ID FROM RecordType WHERE Name='Customer' and sObjectType='Contact' LIMIT 1].ID;
        for(integer i=0;i<n;i++)
        {
            Contact newCont=new Contact();
            newCont.RecordTypeID=recordTypeID;
            newCont.AccountID =accountID;
            newCont.email=defaultEmail;
            newCont.phone=(Math.mod(Integer.valueof(Math.Random()*999),899)+100)+'-'+
                (Math.mod(Integer.valueof(Math.Random()*999),899)+100)+'-'+
                (Math.mod(Integer.valueof(Math.Random()*9999),8999)+1000);
            newCont.age__c=Integer.valueof(Math.floor(Math.Random()*60))+14;
            newCont.mailingStreet=Integer.valueof((Math.Random()*9999))+' '+
                StreetNameList[Integer.valueof(Math.Random()*StreetNameList.size())];
            newCont.mailingCity=CityList[Integer.valueof(Math.Random()*CityList.size())];
            newCont.mailingState=StateList[Integer.valueof(Math.Random()*StateList.size())];
            newCont.mailingPostalCode=String.valueof(Integer.valueof(Math.Random()*99999));
            newCont.BirthDate=Date.today()-Integer.valueof(newCont.age__c*365)-Integer.valueof(Math.random()*364);
            if (Math.Random()>=0.5){
                newCont.sex__c='Male';
                newCont.FirstName=FirstNameMaleList[Integer.valueof(Math.random()*FirstNameMaleList.size())];
                newCont.LastName=LastNameList[Integer.valueof(Math.random()*LastNameList.size())];
            }
            else{
                newCont.sex__c='Female';
                newCont.FirstName=FirstNameFemaleList[Integer.valueof(Math.random()*FirstNameFemaleList.size())];
                newCont.LastName=LastNameList[Integer.valueof(Math.random()*LastNameList.size())];
            }

            List<Schema.PickListEntry> conditionsList=Contact.conditions__c.getDescribe().getPicklistValues();
            newCont.conditions__c='';
            for(Double j=Math.Random()*10;j>6;j=j-3)
            {
                integer randNum=Integer.valueof(Math.floor(Math.Random()*(conditionsList.size())));
                newCont.conditions__c=conditionsList[randNum].getValue()+';'+newCont.conditions__c;
                conditionsList.remove(randNum);
            }
            contactList.add(newCont);

        }
        insert contactList;
    }
    public static void CreateAppointments(integer maxAppointment){
        List<Contact> DocList=[SELECT ID,Language__c FROM Contact WHERE RecordTypeID in (SELECT ID FROM RecordType WHERE SObjectType='Contact' AND Name = 'Doctor')];
        List<Contact> CustList=[SELECT ID FROM Contact WHERE RecordTypeID in (SELECT ID FROM RecordType WHERE SObjectType='Contact' AND Name = 'Customer')];
        List<Residence__C> ResList=[SELECT ID, Doctor__c FROM Residence__c];
        List<Appointment__c> appointList=new List<Appointment__C>();
        Map<ID,ID> ResDocMap=new Map<ID,ID>();
        Map<ID,List<String>> DocLanMap=new Map<ID,List<String>>();
        for (integer i=0;i<ResList.size();i++)
        {
            ResDocMap.put(ResList[i].ID,ResList[i].Doctor__c);
        }
        for(integer i=0;i<DocList.size();i++)
        {
            DocLanMap.put(DocList[i].ID, DocList[i].Language__c.split(';'));
        }

        List<Schema.PicklistEntry> statusList = appointment__c.status__c.getDescribe().getPicklistValues();
        for(integer i=0;i<CustList.size();i++)
        {
            for(integer j=0;j<Integer.valueof(Math.Random()*(maxAppointment-1))+1;j++)
            {
                Appointment__c newAppointment = new Appointment__C();
                newAppointment.Customer__c=CustList[i].ID;
                newAppointment.Residence__c=ResList[Integer.valueof(Math.Random()*(ResList.size()))].ID;
                newAppointment.Doctor__c=ResDocMap.get(newAppointment.Residence__c);
                List<String> lanList=DocLanMap.get(newAppointment.Doctor__c);
                newAppointment.language_preference__c=lanList[Integer.valueof(Math.Random()*(lanList.size()))];
                
                newAppointment.description__c=DescriptionList[Integer.valueof(Math.Random()*(DescriptionList.size()))];
                newAppointment.status__c=statusList[Integer.valueof(Math.Random()*(statusList.size()))].getValue();
                switch on newAppointment.status__c{
                    when 'Confirmed','Changed','Rejected','Rescheduled'{
                        newAppointment.doctor_message__c=defaultDoctorMessage;
                    }
                    when 'Completed'{
                        newAppointment.status__c='Confirmed';
                        
                    }

                }
                newAppointment.start_time__c=DateTime.now().addDays(
                    Integer.valueof((Math.Random()*14)+1)).addHours(
                        Integer.valueof((Math.Random()*4))-2).addMinutes(
                            Integer.valueof((Math.Random()*60)));
                appointList.add(newAppointment);
            }
        }
        insert appointList;
    }
    public static void CreateOfficeLocations(integer n){
        List<Office_Location__c> officeList=new List<Office_Location__c>();
        for (integer i=0;i<n;i++){
            Office_Location__c office = new Office_Location__c();
            office.street_address__c=Integer.valueof((Math.Random()*9999))+' '+
                StreetNameList[Integer.valueof(Math.Random()*StreetNameList.size())];
            office.Name=OfficeNameList[Integer.valueof(Math.Random()*OfficeNameList.size())];
            office.city__c=CityList[Integer.valueof(Math.Random()*CityList.size())];
            office.State__c=StateList[Integer.valueof(Math.Random()*StateList.size())];
            office.zip_code__c=Integer.valueof(Math.Random()*99999);
            office.phone__c=(Math.mod(Integer.valueof(Math.Random()*999),899)+100)+'-'+
                (Math.mod(Integer.valueof(Math.Random()*999),899)+100)+'-'+
                (Math.mod(Integer.valueof(Math.Random()*9999),8999)+1000);
                
            officeList.add(office);
        }
        insert officeList;
    }
    public static void CreateResidences(integer maxRes){
        List<Contact> DocList=[SELECT ID FROM Contact WHERE RecordTypeId in (SELECT ID FROM RecordType WHERE SObjectType='Contact' AND Name = 'Doctor')];
        List<Office_location__c> LocList=[SELECT ID FROM Office_Location__c];
        List<Residence__c> ResList=new List<Residence__c>();
        for (integer i=0; i<DocList.size();i++){
            List<Office_Location__c> TempLocList=LocList;
            Integer randNumRes=Integer.valueof(Math.Random()*(maxRes-1))+1;
            for(integer j=0;j<randNumRes;j++){
                Integer rand=Integer.valueof(Math.Random()*(TempLocList.size()));
                Residence__c newResidence=new Residence__C();
                newResidence.doctor__c=DocList[i].Id;
                newResidence.office_location__c=TempLocList[rand].Id;
                if(tempLocList.size()>1)
                    tempLocList.remove(rand);
                ResList.add(newResidence);
            }
        }
        insert ResList;
    }
    public static void CreateOfficeSurveys(integer maxSurvey){

    }
    public static void CreateDoctorSurveys(integer maxSurvey){

    }
    public static void CreateSearches(integer maxSearch){
        List<Search__c> searchList=new List<Search__c>();
        List<Contact> CustList=[SELECT ID FROM Contact WHERE RecordTypeID in (SELECT ID FROM RecordType WHERE SObjectType='Contact' AND Name = 'Customer')];
        for (integer i=0;i<custList.size();i++){
            for (integer j=0;j<maxSearch;j++){
                Search__c newSearch=new Search__C();
                newSearch.contact__c=custList[i].Id;
                List<Schema.PicklistEntry> specList=contact.specialization__c.getDescribe().getPickListValues();
                newSearch.Specialization__c=specList[Integer.valueof(Math.Random()*specList.size())].getValue();
                List<Schema.PicklistEntry> langList=contact.language__c.getDescribe().getPickListValues();
                newSearch.Language__c=langList[Integer.valueof(Math.Random()*langList.size())].getValue();
                Double randNum=Math.Random();
                if(randNum<0.3){
                    newSearch.sex__c='Male';
                }
                else if(randNum<0.6){
                    newSearch.sex__c='Female';
                }
                //newSearch.TimeStamp__c=DateTime.now().addDays(
                //    -1*Integer.valueof((Math.Random()*14)+1)).addHours(
                //        Integer.valueof((Math.Random()*4))-2).addMinutes(
                //            Integer.valueof((Math.Random()*60)));
                searchList.add(newSearch);
            }
        }
        insert searchList;
    }
    public static void DeleteAll(){
        DELETE [SELECT ID FROM Search__C];
        DELETE [SELECT ID FROM Appointment__c];
        DELETE [SELECT ID FROM Residence__c];
        DELETE [SELECT ID FROM Office_Location__c];
        DELETE [SELECT ID FROM Case];
        DELETE [SELECT ID FROM Contact];
    }
}