babbageprod/force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APPT-{00000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

finalproject/force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Time and Date of the Appointment</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/classes/UpdateCompletedAppointments.cls
global class UpdateCompletedAppointments implements Schedulable {
    global void execute(SchedulableContext ctx){
        // we're updating appointments that have been completed (i.e. they're status is confirmed and they
        // are in the past) in order to activate a process that sends a survey to the patient
        List<Appointment__c> completedAppointments = [SELECT Id, Status__c FROM Appointment__c WHERE 
                                                      Status__c='Confirmed' AND Start_Time__c <:DateTime.now()];
        for(Appointment__c a : completedAppointments){
            a.Status__c = 'Completed';
        }
        update completedAppointments;
    }
}