finalproject/force-app/main/default/objects/Contact/fields/Languages__c.field-meta.xml
<CustomField>
    <fullName>Languages__c</fullName>
    <label>Languages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
                <isActive>false</isActive>
                <label>Arabic</label>
            </value>
            <value>
                <fullName>Cherokee</fullName>
                <isActive>false</isActive>
                <label>Cherokee</label>
            </value>
            <value>
                <fullName>Korean</fullName>
                <isActive>false</isActive>
                <label>Korean</label>
            </value>
            <value>
                <fullName>Vietnamese</fullName>
                <isActive>false</isActive>
                <label>Vietnamese</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

finalproject/force-app/main/default/objects/Contact/fields/Speciality__c.field-meta.xml
<CustomField>
    <fullName>Speciality__c</fullName>
    <label>Speciality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Immunology</fullName>
            </value>
            <value>
                <fullName>Anesthesiology</fullName>
            </value>
            <value>
                <fullName>Dermatology</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
            <value>
                <fullName>Ophthalmology</fullName>
            </value>
            <value>
                <fullName>Pathology</fullName>
            </value>
            <value>
                <fullName>Psychiatry</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

finalproject/force-app/main/default/classes/TestDoctorTraits.cls
@IsTest
public with sharing class TestDoctorTraits {
	@IsTest (seeAllData=true)
    static public void runTest() {	
        List<String> genders = new List<String>{};
            for ( PicklistEntry gend : Contact.Gender__c.getDescribe().getPicklistValues() ) {
                genders.add( gend.getLabel() );
            }
        
        List<String> languages = new List<String>{};
            for ( PicklistEntry lang : 	Contact.Languages__c.getDescribe().getPicklistValues() ) {
                languages.add( lang.getLabel() );
            }
        
        List<String> specialities = new List<String>{};
            for ( PicklistEntry spec : 	Contact.Speciality__c.getDescribe().getPicklistValues() ) {
                specialities.add( spec.getLabel() );
            }
        
        System.AssertEquals(DoctorTraits.specOptions(), specialities);
        System.AssertEquals(DoctorTraits.genderOptions(), genders);
        System.AssertEquals(DoctorTraits.langOptions(), languages);
        
        System.AssertEquals(DoctorTraits.recTypeCust, '0126g000000Mc5UAAS');
        System.AssertEquals(DoctorTraits.recTypeDoc, '0126g000000Mc5VAAS');
    }
    
}