finalproject/force-app/main/default/objects/Contact/fields/Languages__c.field-meta.xml
<CustomField>
    <fullName>Languages__c</fullName>
    <label>Languages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
                <isActive>false</isActive>
                <label>Arabic</label>
            </value>
            <value>
                <fullName>Cherokee</fullName>
                <isActive>false</isActive>
                <label>Cherokee</label>
            </value>
            <value>
                <fullName>Korean</fullName>
                <isActive>false</isActive>
                <label>Korean</label>
            </value>
            <value>
                <fullName>Vietnamese</fullName>
                <isActive>false</isActive>
                <label>Vietnamese</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

finalproject/force-app/main/default/objects/Contact/fields/Speciality__c.field-meta.xml
<CustomField>
    <fullName>Speciality__c</fullName>
    <label>Speciality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Immunology</fullName>
            </value>
            <value>
                <fullName>Anesthesiology</fullName>
            </value>
            <value>
                <fullName>Dermatology</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
            <value>
                <fullName>Ophthalmology</fullName>
            </value>
            <value>
                <fullName>Pathology</fullName>
            </value>
            <value>
                <fullName>Psychiatry</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

finalproject/force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>This is the custom record type for the Customer profile.  It hides custom Doctor picklists.</description>
    <label>Customer</label>
</RecordType>

finalproject/force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <description>Record type showing all custom doctor fields.</description>
    <label>Doctor</label>
</RecordType>

finalproject/force-app/main/default/classes/DoctorTraits.cls
// Interior utility class for accessing picklist arrays
public class DoctorTraits 
{	// Save record type ID's for contact as final strings
    public static final String recTypeDoc = Schema.SObjectType.Contact.getRecordTypeInfosByName()
                                        			.get('Doctor').getRecordTypeId();
    public static final String recTypeCust = Schema.SObjectType.Contact.getRecordTypeInfosByName()
                                        			.get('Customer').getRecordTypeId();
    
    // Fetch doctor picklist fields and return them as lists of strings
    static public List<String> genderOptions()
    {   List<String> genders = new List<String>{};
        for ( PicklistEntry gend : Contact.Gender__c.getDescribe().getPicklistValues() )
            genders.add( gend.getLabel() );
        return genders;
    }
    static public List<String> langOptions()
    {   List<String> languages = new List<String>{};
        for ( PicklistEntry lang : 	Contact.Languages__c.getDescribe().getPicklistValues() )
            languages.add( lang.getLabel() );
        return languages;
    }
    static public List<String> specOptions()
    {   List<String> specialities = new List<String>{};
        for ( PicklistEntry spec : 	Contact.Speciality__c.getDescribe().getPicklistValues() )
            specialities.add( spec.getLabel() );
        return specialities; 
    }
}