finalproject/force-app/main/default/objects/Contact/fields/Languages__c.field-meta.xml
<CustomField>
    <fullName>Languages__c</fullName>
    <label>Languages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
                <isActive>false</isActive>
                <label>Arabic</label>
            </value>
            <value>
                <fullName>Cherokee</fullName>
                <isActive>false</isActive>
                <label>Cherokee</label>
            </value>
            <value>
                <fullName>Korean</fullName>
                <isActive>false</isActive>
                <label>Korean</label>
            </value>
            <value>
                <fullName>Vietnamese</fullName>
                <isActive>false</isActive>
                <label>Vietnamese</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

finalproject/force-app/main/default/objects/Contact/fields/Speciality__c.field-meta.xml
<CustomField>
    <fullName>Speciality__c</fullName>
    <label>Speciality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Immunology</fullName>
            </value>
            <value>
                <fullName>Anesthesiology</fullName>
            </value>
            <value>
                <fullName>Dermatology</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
            <value>
                <fullName>Ophthalmology</fullName>
            </value>
            <value>
                <fullName>Pathology</fullName>
            </value>
            <value>
                <fullName>Psychiatry</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

finalproject/force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>This is the custom record type for the Customer profile.  It hides custom Doctor picklists.</description>
    <label>Customer</label>
</RecordType>

finalproject/force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <description>Record type showing all custom doctor fields.</description>
    <label>Doctor</label>
</RecordType>

finalproject/force-app/main/default/classes/ContactController.cls
public with sharing class ContactController {
/*   
     @AuraEnabled
    public static List<String> getAvailableDoctorSpecialityOptions() {
        List<String> pickListValuesList= new List<String>();
		Schema.DescribeFieldResult fieldResult = Contact.Speciality__c.getDescribe();
		List<Schema.PicklistEntry> spec = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : spec){
			pickListValuesList.add(pickListVal.getValue());
		}     system.debug('speciality');
		return pickListValuesList;
    }

    // Returning a list of Strings filled with the picklist values of Gender__c
    
    public static List<String> getAvailableDoctorGenderrOptions() {
        
        List<String> pickListValuesList= new List<String>();
		Schema.DescribeFieldResult fieldResult = Contact.Gender__c.getDescribe();
		List<Schema.PicklistEntry> gend = fieldResult.getPicklistValues();
        system.debug(fieldResult.getPicklistValues());
		for( Schema.PicklistEntry pickListVal : gend){
			pickListValuesList.add(pickListVal.getValue());
		}     system.debug('language');
		return pickListValuesList;
    }

    // Returning a list of Strings filled with the picklist values of Languages__c
   
    public static List<String> getAvailableDoctorLanguageeOptions() {
        List<String> pickListValuesList= new List<String>();
		Schema.DescribeFieldResult fieldResult = Contact.Languages__c.getDescribe();
		List<Schema.PicklistEntry> lang = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : lang){
			pickListValuesList.add(pickListVal.getValue());
		}
        system.debug('language');
		return pickListValuesList;
    }
  
    public static List<Contact> getDoctorss(String specialty, String gender, String language) {
       //List<Contact> Docs = new List<Contact>();
       // Final String recTypeDoc = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Doctor').getRecordTypeId();
        //docList = database.query('Select Id, Name, Speciality__c, Gender__c, Languages__c From Contact Where RecordTypeId=:recTypeDoc AND Speciality__c=:specialty AND Gender__c=:gender AND Languages__c includes :language');
		//docList = database.query('Select Id, Name, Speciality__c, Gender__c, Languages__c From Contact Where RecordTypeId=:recTypeDoc limit 5');
        
        //return docList;
        
        Id recTypeDoc = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Doctor').getRecordTypeId();
 
             Id devRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        system.debug(recTypeDoc+'  Cust   '+devRecordTypeId);
        
        //Qyery 10 accounts
       // List<Contact> Docs = database.query('Select Id, Name, Speciality__c, Gender__c, Languages__c From Contact Where RecordTypeId=:devRecordTypeId limit 10');
       List<Contact>  Docs = database.query('Select Id, Name, Speciality__c, Gender__c, Languages__c From Contact Where RecordTypeId=:recTypeDoc AND Speciality__c=:specialty AND Gender__c=:gender'); // AND Languages__c includes :language');
        //return list of accounts
        return Docs;
        
    } 

    @AuraEnabled

    public static List <Contact> fetchAccounts() {
        Id recTypeDoc = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Doctor').getRecordTypeId();
 
             Id devRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
       // system.debug(recTypeDoc+'  Cust   '+devRecordTypeId);
        //Qyery 10 accounts
        List<Contact> docList = database.query('Select Id, Name, Speciality__c, Gender__c, Languages__c From Contact Where RecordTypeId=:devRecordTypeId');
        
        //return list of accounts
             
        
        return docList;
    } 
*/}