force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Doctor)</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>End Time of the Appointment</description>
    <formula>Start_Time__c + 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Time and Date of the Appointment</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unconfirmed</fullName>
                <default>true</default>
                <label>Unconfirmed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

finalproject/force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <description>Record type showing all custom doctor fields.</description>
    <label>Doctor</label>
</RecordType>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <formula>First_Name__c +  Middle_Initial__c +  Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NPFT_Project1/force-app/main/default/objects/Doctor__c/fields/Specialty__c.field-meta.xml
<CustomField>
    <fullName>Specialty__c</fullName>
    <label>Specialty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allergist</fullName>
            </value>
            <value>
                <fullName>Cardiologist</fullName>
            </value>
            <value>
                <fullName>Dermatologist</fullName>
            </value>
            <value>
                <fullName>Family Medicine</fullName>
            </value>
            <value>
                <fullName>Neurosurgeon</fullName>
            </value>
            <value>
                <fullName>OBGYN</fullName>
            </value>
            <value>
                <fullName>Oncologist</fullName>
            </value>
            <value>
                <fullName>Orthopedic Specialist</fullName>
            </value>
            <value>
                <fullName>Orthopedic Surgeon</fullName>
            </value>
            <value>
                <fullName>Pediatrician</fullName>
            </value>
            <value>
                <fullName>Plastic Surgeon</fullName>
            </value>
            <value>
                <fullName>Radiologist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DoctorController.cls
public with sharing class DoctorController {
    
    public String choosenApp {get; set;}
    public String userID = UserInfo.getUserId();
    User user = database.query('Select FirstName, LastName From User Where ID=\'' + UserID + '\' Limit 1');
   	Doctor__c doctor = database.query('Select Name, ID, First_Name__c, Last_Name__c, Specialty__c, Email__c From Doctor__c Where Last_Name__c=\'' + user.LastName + '\' Limit 1');
    public Appointment__c returnedApp {Get; Set { returnedApp = value; }}
     
    
    // Query for Docter using last name of the user logged in
    public List<Doctor__c> GetDoctor() {
        List<Doctor__c> docList = database.query('Select First_Name__c, Last_Name__c, Specialty__c, Email__c From Doctor__c Where Last_Name__c=\'' + user.LastName + '\'');
    	return docList;
    }
    
    // Query for Appointments using name of the doctor assiated with the user logged in
    // Sort the Query by Start time and dont show any appointments already past
    public List<Appointment__c> GetApprovedAppointments() {
        ID docID = doctor.ID;
        datetime present = system.now();
        List<Appointment__c> appList = database.query('Select Name, Start_Time__c, End_Time__c, Customer__c, Description__c From Appointment__c Where Doctor__c=:docID AND End_Time__c >:present AND Status__c=\'Approved\'');
        return appList;
    }
    
    public List<SelectOption> GetPendingAppointments() {
           	ID docID = doctor.ID;
            datetime present = system.now();
            List<Appointment__c> appList = database.query('Select ID From Appointment__c Where Doctor__c=:docID AND End_Time__c >:present AND Status__c=\'Pending\'');
            List<SelectOption> appNames = new List<SelectOption>();
            for (Appointment__c app : appList) {
                appNames.add(new SelectOption(app.ID, app.ID));
            }
            return appNames;
    }
    
    public void ViewAppointmentDetails() {
        if (choosenApp == null) {
        	List<Appointment__c> appList = database.query('Select Name, Start_Time__c, End_Time__c, Customer__r.FullName__c, Description__c, status__c From Appointment__c');            
        	Appointment__c app = appList[0];
            returnedApp = app;
        
        } else {
            ID appID = (ID) choosenApp;
        	Appointment__c app = database.query('Select Name, Start_Time__c, End_Time__c, Customer__r.FullName__c, Description__c, status__c From Appointment__c Where Id=:appID');
    		returnedApp = app;
        }
	}
    
    //Status updates to Confirmed
    public void AcceptAppointment() {
        ID appID = (ID) choosenApp;
        Appointment__c app = database.query('Select Name, Start_Time__c, End_Time__c, Customer__r.FullName__c, Description__c, status__c From Appointment__c Where Id=:appID');
        app.Status__c = 'Confirmed';
        update app;
    }
    
    //Status updates to Cancelled
    public void CancelAppointment() {
        ID appID = (ID) choosenApp;
        Appointment__c app = database.query('Select Name, Start_Time__c, End_Time__c, Customer__r.FullName__c, Description__c, status__c From Appointment__c Where Id=:appID');
        app.Status__c = 'Cancelled';
        update app;
    }
}