force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <label>Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Doctor)</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Time and Date of the Appointment</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unconfirmed</fullName>
                <default>true</default>
                <label>Unconfirmed</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CustomerAppointmentsController.cls
public without sharing class CustomerAppointmentsController {
    public String typeAppointment;
    public String statusPref {get; set;}
    public List<Appointment__c> result {get; set;}


    public List<SelectOption> statusList{get
    {
        List<SelectOption> statusOptions=new List<SelectOption>();
        List<Schema.PicklistEntry> statusPicklist = Appointment__c.status__c.getDescribe().getPickListValues();
        for (Schema.PicklistEntry entry : statusPicklist)
        {
            statusOptions.add(new SelectOption(entry.getValue(),entry.getLabel()));
        }
        return statusOptions;
    }}

    public CustomerAppointmentsController(){}

    public void updateAppointments()
    {
        string queryString='SELECT Description__c, Doctor__c, Status__c, Start_Time__c FROM Appointment__c';
        if(statusPref.length()>2){
            queryString += ' WHERE';
            statusPref=statusPref.substring(1,statusPref.length()-1); //gets ride of brackets
            statusPref=statusPref.replace(', ','\',\'');
            queryString=queryString+' Status__c IN(\''+statusPref+'\')';
            System.debug(queryString);
        }
        result = Database.query(queryString);
    }
}