finalproject/force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>Appointment-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

finalproject/force-app/main/default/objects/Appointment__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <label>Customer Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Customer Contact)</relationshipLabel>
    <relationshipName>CustomerAppointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Doctor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Doctor_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Doctor Contact)</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Time and Date of the Appointment</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/fields/Flagged__c.field-meta.xml
<CustomField>
    <fullName>Flagged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flagged</label>
    <type>Checkbox</type>
</CustomField>

finalproject/force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>This is the custom record type for the Customer profile.  It hides custom Doctor picklists.</description>
    <label>Customer</label>
</RecordType>

finalproject/force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <description>Record type showing all custom doctor fields.</description>
    <label>Doctor</label>
</RecordType>

finalproject/force-app/main/default/classes/FlagDoctors.cls
global class FlagDoctors implements Schedulable {
    global void execute(SchedulableContext ctx) {
        // Query for all Appointments between one year and sizx months ago
        // and all Appointments between six months ago and now
        Contact[] docList = new List<Contact>(); 
        DateTime cutoffMin = DateTime.now() - 365;
        DateTime cutoffMax = DateTime.now() - 183;
        List<Appointment__c> appList = database.query('Select Id, Customer_Contact__c, Doctor_Contact__c, Start_Time__c From Appointment__c Where Start_Time__c >:cutoffMin AND Start_Time__c <:cutoffMax');
        List<Appointment__c> appList2 = database.query('Select Id, Customer_Contact__c, Doctor_Contact__c, Start_Time__c From Appointment__c Where Start_Time__c <:cutoffMin');
        
        // iterate through both lists of appoints to find matches
        // if theres no match that means that the customer didn't reschedule with the doctor 
        // in the second half of the year and is then flagged
        Boolean flagged = true;
        for (Appointment__c app : appList) {
            for (Appointment__c app2 : appList2) {
                if ((app.Doctor_Contact__c == app2.Doctor_Contact__c) && (app.Customer_Contact__c == app.Customer_Contact__c)) {
                    flagged = false;
                } 
                Contact doc = new Contact();
                doc.Id = app.Doctor_Contact__c;
                doc.Flagged__c = flagged;
                docList.add(doc);
            }
        }
        // update the list of flagged doctors
    	update docList;
    }
}