finalproject/force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>Appointment-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

finalproject/force-app/main/default/objects/Appointment__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <label>Customer Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Customer Contact)</relationshipLabel>
    <relationshipName>CustomerAppointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Doctor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Doctor_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Doctor Contact)</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Time and Date of the Appointment</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/fields/Flagged__c.field-meta.xml
<CustomField>
    <fullName>Flagged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Flagged</label>
    <type>Checkbox</type>
</CustomField>

finalproject/force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>This is the custom record type for the Customer profile.  It hides custom Doctor picklists.</description>
    <label>Customer</label>
</RecordType>

finalproject/force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <description>Record type showing all custom doctor fields.</description>
    <label>Doctor</label>
</RecordType>

finalproject/force-app/main/default/classes/TestFlagDoctors.cls
@isTest
private class TestFlagDoctors {
    static testmethod void testScheduledJob() {
        // Create Test Doctor and Customer
        Final String recTypeDoc = Schema.SObjectType.Contact.getRecordTypeInfosByName()
                                        .get('Doctor').getRecordTypeId();
        Final String recTypeCust = Schema.SObjectType.Contact.getRecordTypeInfosByName()
                                        .get('Customer').getRecordTypeId();
        Contact doc = new Contact();
        	doc.LastName = 'Dawkins';
        	doc.RecordTypeId = recTypeDoc;
        Contact cust = new Contact();
        	cust.LastName = 'Henry';
        	cust.RecordTypeId = recTypeCust;
        String CRON_EXP = '0 0 0 1 10 ? 2020';
        
        
        //Insert contacts and Appointment
        insert doc;
        insert cust;
        
        
        // Create Appointment between six months and one year ago
        Appointment__c app = new Appointment__c();
        	app.Doctor_Contact__c = doc.Id;
        	app.Customer_Contact__c = cust.Id;
        	app.Start_Time__c = DateTime.now() - 200;
        insert app;
        
        // Query for the flagged field of the doctor we just inserted
        ID docID = doc.ID;
        Contact doctor = database.query('Select Flagged__c From Contact Where ID =: docID');
        Boolean flagged = doctor.Flagged__c;
        System.assertEquals(false, flagged);
        
        Test.startTest();
        String jobId = System.schedule('ScheduledApexTest',
            CRON_EXP, 
            new FlagDoctors());
        
        
        Test.stopTest();
        
        // Assert that flagged field was changed from false to true
        System.assertEquals(true, flagged);
    }
}