finalproject/force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>Appointment-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

finalproject/force-app/main/default/objects/Appointment__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <label>Customer Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Customer Contact)</relationshipLabel>
    <relationshipName>CustomerAppointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message explaining why an Appointment was cancelled</description>
    <label>Message</label>
    <type>TextArea</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status denoting if the Appointment is accepted or not by the doctor</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

finalproject/force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>This is the custom record type for the Customer profile.  It hides custom Doctor picklists.</description>
    <label>Customer</label>
</RecordType>

finalproject/force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <description>Record type showing all custom doctor fields.</description>
    <label>Doctor</label>
</RecordType>

finalproject/force-app/main/default/classes/DoctorHomeControllerTest.cls
@isTest
public class DoctorHomeControllerTest 
{
    @isTest
    public static void runTests ()
    {
        /* TODO: Code a test that:
				- Sets a mock doctor with some appts
				- Fetches appts with getDoctorAppts() as if that doctor was viewing the page
				- Inserts a fake appointment
				- Updates the appointment with UpdateAppointment()
		*/
        DataFactory.createData(1); // create one doctor, one customer, and one appt between them
        Contact customer = [ 	SELECT Id
                            	FROM Contact 
                            	WHERE RecordTypeId =: DoctorTraits.recTypeCust 
                            	AND LastName LIKE '%Last0' 
                           ][0];
        Appointment__c myApp = [ 	SELECT Id, Status__c, Message__c 
                                	FROM Appointment__c 
                                	WHERE Customer_Contact__c =: customer.Id 
                               ];
        DoctorHomeController.updateAppointment( 'Test', 'Reject', (String) myApp.id );
        Appointment__c checkApp = 
        	[	SELECT Id, Message__c, Status__c
                FROM Appointment__c
                WHERE Id =: myApp.Id
            ];
        System.assertEquals(checkApp.Status__c, 'Cancelled');
        System.assertEquals(checkApp.Message__c, 'Test');
    }
}