finalproject/force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>Appointment-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

finalproject/force-app/main/default/objects/Appointment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments2</relationshipLabel>
    <relationshipName>Appointments2</relationshipName>
    <type>Lookup</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <label>Customer Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Customer Contact)</relationshipLabel>
    <relationshipName>CustomerAppointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Doctor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Doctor_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appointments (Doctor Contact)</relationshipLabel>
    <relationshipName>Appointments1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Residence__c.field-meta.xml
<CustomField>
    <fullName>Residence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The location where this appointment is happening.</description>
    <label>Residence</label>
    <referenceTo>Residence__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Time and Date of the Appointment</description>
    <label>Start Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

finalproject/force-app/main/default/objects/Appointment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status denoting if the Appointment is accepted or not by the doctor</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

finalproject/force-app/main/default/objects/Contact/fields/Languages__c.field-meta.xml
<CustomField>
    <fullName>Languages__c</fullName>
    <label>Languages</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Russian</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
                <isActive>false</isActive>
                <label>Arabic</label>
            </value>
            <value>
                <fullName>Cherokee</fullName>
                <isActive>false</isActive>
                <label>Cherokee</label>
            </value>
            <value>
                <fullName>Korean</fullName>
                <isActive>false</isActive>
                <label>Korean</label>
            </value>
            <value>
                <fullName>Vietnamese</fullName>
                <isActive>false</isActive>
                <label>Vietnamese</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

finalproject/force-app/main/default/objects/Contact/fields/Speciality__c.field-meta.xml
<CustomField>
    <fullName>Speciality__c</fullName>
    <label>Speciality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Immunology</fullName>
            </value>
            <value>
                <fullName>Anesthesiology</fullName>
            </value>
            <value>
                <fullName>Dermatology</fullName>
            </value>
            <value>
                <fullName>Neurology</fullName>
            </value>
            <value>
                <fullName>Ophthalmology</fullName>
            </value>
            <value>
                <fullName>Pathology</fullName>
            </value>
            <value>
                <fullName>Psychiatry</fullName>
            </value>
            <value>
                <fullName>Urology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

finalproject/force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <description>Record type showing all custom doctor fields.</description>
    <label>Doctor</label>
</RecordType>

finalproject/force-app/main/default/objects/ContactResidence__c/ContactResidence__c.object-meta.xml
<CustomObject>
    <label>ContactResidence</label>
    <nameField>
        <displayFormat>ContactResidence-{0000}</displayFormat>
        <label>ContactResidence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ContactResidences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

finalproject/force-app/main/default/objects/ContactResidence__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>ContactResidences</relationshipLabel>
    <relationshipName>ContactResidences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

finalproject/force-app/main/default/objects/ContactResidence__c/fields/Residence__c.field-meta.xml
<CustomField>
    <fullName>Residence__c</fullName>
    <label>Residence</label>
    <referenceTo>Residence__c</referenceTo>
    <relationshipLabel>ContactResidences</relationshipLabel>
    <relationshipName>ContactResidences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

finalproject/force-app/main/default/objects/Residence__c/Residence__c.object-meta.xml
<CustomObject>
    <description>Place where Doctor can hold Appointments</description>
    <label>Residence</label>
    <nameField>
        <label>Residence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residence</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

finalproject/force-app/main/default/objects/Residence__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

finalproject/force-app/main/default/objects/Residence__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

finalproject/force-app/main/default/objects/Residence__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

finalproject/force-app/main/default/objects/Residence__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

finalproject/force-app/main/default/classes/DataFactory.cls
public class DataFactory 
{	
    // Save doctor picklist vals as lists of strings
    static private List<String> genders = DoctorTraits.genderOptions();
    static private List<String> languages = DoctorTraits.langOptions();
    static private List<String> specialities = DoctorTraits.specOptions();
    
    public static void createData( Integer n )
    {   // Initialize list objects to populate and insert
        List<Appointment__c> appList = new List<Appointment__c>();
        List<Contact> drList = new List<Contact>();
        List<Contact> custList = new List<Contact>();
        List<ContactResidence__c> conResList = new List<ContactResidence__c>();
        Account southernHeart;
        try // Look for Southern Heart account in the org
        {	southernHeart = [ SELECT Id, Name FROM Account WHERE Name = 'Southern Heart' LIMIT 1 ];
        } catch ( QueryException qe )
        {	// Add Southern Heart account if it doesn't exist already
        	southernHeart = new Account(name = 'Southern Heart');
         	insert southernHeart;
            southernHeart.IsPartner = true;
            update southernHeart;
        }
        // Create 2 residences
        Residence__c reston = new Residence__c 
            (	Name = 'Robert E. Lee Memorial Hospital',
                Street_Address__c = '11730 Plaza America Blvd',
             	City__c = 'Reston',
             	Postal_Code__c = 20170,
             	State__c = 'VA',
             	Country__c = 'US'
            ); upsert reston;
        Residence__c herndon = new Residence__c
        	(	Name = 'Southern Hospitality Family Care',
                Street_Address__c = '2282 Astoria Drive',
             	City__c = 'Herndon',
             	Postal_Code__c = 20190,
             	State__c = 'VA',
             	Country__c = 'US'
            ); upsert herndon;
        // Create n Doctors and n Customers
        for(Integer i = 0 ; i < n ; i++)
        {   Contact obj = new Contact();
            obj.AccountId = southernHeart.Id;
            obj.LastName = 'Last'+i;
            obj.recordTypeId = DoctorTraits.recTypeCust;
            custList.add(obj);
        }
        for (Integer i = 0 ; i < n ; i++)
        {	Contact obj = new Contact();
            obj.AccountId = southernHeart.Id;
            obj.LastName = 'DrLast'+i;
            obj.recordTypeId = DoctorTraits.recTypeDoc;
         	obj.Gender__c = genders[ Integer.valueOf( Math.random() * genders.size() ) ];
         	obj.Languages__c = languages[ Integer.valueOf( Math.random() * languages.size() ) ];
         	obj.Speciality__c = specialities[ Integer.valueOf( Math.random() * specialities.size() ) ];
            // obj.Gender__c = (0 == Math.mod( i , 2 ) ? 'Female': 'Male');
            drList.add(obj);
        } 
        upsert custList; upsert drList;
        
        // Add each doctor to the Reston residence using junction object
        for( Contact dr : drList )
        {
            ContactResidence__c obj = new ContactResidence__c();
            obj.Contact__c = dr.Id;
            obj.Residence__c = reston.Id;
            conResList.add(obj);
        }
        insert conResList;
        
        // Create n appointments between doctors and customers at the Reston location
        for(Integer j = 0; j < n; j++)
        {
            appList.add (new Appointment__c(    Status__c = 'Pending',
                                                Start_Time__c = DateTime.now().addDays(j),
                                                Customer_Contact__c = custList.get( j ).Id,
                                                Doctor_Contact__c = drList.get( j ).Id,
            									Residence__c = reston.Id
                         )					);
        }
        insert appList;
    }
    // Create many appointments between the same two contacts
    public static void CreateAppts (Contact dr, Contact cust, Integer n)
    {	List<Appointment__c> applist = new List<Appointment__c>();
     	for ( Integer i = 0 ; i < 1 ; i++ )
        {	applist.add( new Appointment__c	(   Status__c = 'Pending',
                                                Start_Time__c = DateTime.now().addDays(i),
                                                Customer_Contact__c = cust.Id,
                                                Doctor_Contact__c = dr.Id
                                          	)
                        );
        }
     	insert applist;
    }
    public static void DestroyData ()
    {
        List<Contact> dummyContacts = [ SELECT Id, LastName
                                       	FROM Contact 
                                       	WHERE LastName LIKE '%Last%'
                                      ];
        // List<Appointment__c> dummyAppts = [	SELECT Id 
        //                                   	FROM Appointment__c
        //                                  ];
        delete dummyContacts;
    }
}