babbageprod/force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexes</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Specialties</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

babbageprod/force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <label>Doctor</label>
</RecordType>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Office_Location__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

babbageprod/force-app/main/default/objects/Office_Location__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

babbageprod/force-app/main/default/objects/Office_Location__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>128</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

babbageprod/force-app/main/default/objects/Office_Location__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

babbageprod/force-app/main/default/objects/Residence__c/Residence__c.object-meta.xml
<CustomObject>
    <label>Residence</label>
    <nameField>
        <label>Residence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

finalproject/force-app/main/default/objects/Residence__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

babbageprod/force-app/main/default/objects/Residence__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Residences</relationshipLabel>
    <relationshipName>Residences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/objects/Residence__c/fields/Office_Location__c.field-meta.xml
<CustomField>
    <fullName>Office_Location__c</fullName>
    <label>Office Location</label>
    <referenceTo>Office_Location__c</referenceTo>
    <relationshipLabel>Residences</relationshipLabel>
    <relationshipName>Residences</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

finalproject/force-app/main/default/objects/Residence__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

babbageprod/force-app/main/default/globalValueSets/Languages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>English</fullName>
        <default>true</default>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <masterLabel>Languages</masterLabel>
</GlobalValueSet>

babbageprod/force-app/main/default/globalValueSets/Sexes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <masterLabel>Sexes</masterLabel>
</GlobalValueSet>

babbageprod/force-app/main/default/globalValueSets/Specialties.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cardiologist</fullName>
    </customValue>
    <customValue>
        <fullName>Chiropractor</fullName>
    </customValue>
    <customValue>
        <fullName>General Practitioner</fullName>
    </customValue>
    <customValue>
        <fullName>Oncologist</fullName>
    </customValue>
    <customValue>
        <fullName>OBGYN</fullName>
    </customValue>
    <customValue>
        <fullName>Proctologist</fullName>
    </customValue>
    <masterLabel>Specialties</masterLabel>
</GlobalValueSet>

babbageprod/force-app/main/default/classes/UtilityTestClass.cls
// utility class to create test data used by functions in TestUpdateCompletedAppointments and 
// TestCustomerSearchRequestController apex classes
@isTest
public class UtilityTestClass {
    public static void testFactory(){
        // insert a doctor
        Account testAccount = new Account(Name='Test');
        insert testAccount;
        testAccount = [SELECT Id FROM Account WHERE Name='Test' LIMIT 1];
        
        //insert doctor;
		Id recordTypeId=[SELECT ID FROM RecordType WHERE Name='Doctor' and sObjectType='Contact' LIMIT 1].Id;
        Contact testDoctor = new Contact(AccountId=testAccount.Id, FirstName='Test', LastName='Doctor', 
                                         Sex__c='Male', Specialization__c='Proctologist', 
                                         Email='test@gmail.com', Language__c='English;Spanish', RecordTypeId=recordTypeId);
        insert testDoctor;
        
        // insert a residence
        Office_Location__c testOffice = new Office_Location__c(Name='Test', Zip_Code__c=12345, State__c='PA',
                                                               City__c='Meadville', 
                                                               Street_Address__c='12345 Way');
        insert testOffice;
        testOffice = [SELECT Id FROM Office_Location__c WHERE Name='Test' LIMIT 1];
        testDoctor = [SELECT Id FROM Contact WHERE Name='Test Doctor' LIMIT 1];
        Residence__c testResidence = new Residence__c(Doctor__c=testDoctor.Id, 
                                                      Office_Location__c=testOffice.Id);
        insert testResidence;
        
        // insert a customer
        recordTypeId=[SELECT ID FROM RecordType WHERE Name='Customer' and sObjectType='Contact' LIMIT 1].Id;
        Contact testCustomer = new Contact(AccountId=testAccount.Id, Email='test@gmail.com', 
                                           FirstName='Test', LastName='Customer', RecordTypeId=recordTypeId);
        insert testCustomer;
    }
}