babbageprod/force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexes</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Specialties</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

babbageprod/force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <label>Doctor</label>
</RecordType>

babbageprod/force-app/main/default/objects/Residence__c/Residence__c.object-meta.xml
<CustomObject>
    <label>Residence</label>
    <nameField>
        <label>Residence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Residence__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Residences</relationshipLabel>
    <relationshipName>Residences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/objects/Search__c/Search__c.object-meta.xml
<CustomObject>
    <label>Search</label>
    <nameField>
        <displayFormat>Search-{00000}</displayFormat>
        <label>Search Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Searches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Search__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Searches</relationshipLabel>
    <relationshipName>Searches</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

babbageprod/force-app/main/default/objects/Search__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Search__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexes</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Search__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Specialties</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/globalValueSets/Languages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>English</fullName>
        <default>true</default>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <masterLabel>Languages</masterLabel>
</GlobalValueSet>

babbageprod/force-app/main/default/globalValueSets/Sexes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <masterLabel>Sexes</masterLabel>
</GlobalValueSet>

babbageprod/force-app/main/default/globalValueSets/Specialties.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cardiologist</fullName>
    </customValue>
    <customValue>
        <fullName>Chiropractor</fullName>
    </customValue>
    <customValue>
        <fullName>General Practitioner</fullName>
    </customValue>
    <customValue>
        <fullName>Oncologist</fullName>
    </customValue>
    <customValue>
        <fullName>OBGYN</fullName>
    </customValue>
    <customValue>
        <fullName>Proctologist</fullName>
    </customValue>
    <masterLabel>Specialties</masterLabel>
</GlobalValueSet>

babbageprod/force-app/main/default/classes/TestCustomerSearchRequestController.cls
@isTest
public class TestCustomerSearchRequestController {
    @isTest static void testReturnMatchingDoctors(){
        // test with no specifications, gender specified, language specified, specialization specified
        UtilityTestClass.testFactory();
        String male = 'Male';
        String spanish = 'Spanish';
        String proctologist = 'Proctologist';
        String generalTest = 'SELECT Id FROM Residence__c';
        String genderTest = 'SELECT Id FROM Residence__c WHERE Doctor__r.Sex__c=\'' + male + '\'';
        String languageTest = 'SELECT Id FROM Residence__c WHERE Doctor__r.Language__c INCLUDES(\'' +
            spanish + '\')';
        String specializationTest = 'SELECT Id FROM Residence__c WHERE Doctor__r.Specialization__c=\'' +
            proctologist + '\'';
        List<Residence__c> generalResults = CustomerSearchRequestPageController.returnMatchingDoctors(
            generalTest);
        List<Residence__c> genderResults = CustomerSearchRequestPageController.returnMatchingDoctors(
            genderTest);
        List<Residence__c> languageResults = CustomerSearchRequestPageController.returnMatchingDoctors(
            languageTest);
        List<Residence__c> specializationResults = CustomerSearchRequestPageController.returnMatchingDoctors(
            specializationTest);
        Id expectedId = [SELECT Id FROM Residence__c LIMIT 1].Id;
        System.assertEquals(expectedId, generalResults[0].Id);
        System.assertEquals(expectedId, genderResults[0].Id);
        System.assertEquals(expectedId, languageResults[0].Id);
        System.assertEquals(expectedId, specializationResults[0].Id);
    }
    
    @isTest static void testInsertSearchRecord(){
        // test insertion of search record
        UtilityTestClass.testFactory();
        Contact testCustomer = [SELECT Id FROM Contact WHERE Name='Test Customer' LIMIT 1];
        Search__c testSearch = new Search__c(Contact__c=testCustomer.Id);
        CustomerSearchRequestPageController.insertSearchRecord(testSearch);
        testSearch = [SELECT Id, Contact__c FROM Search__c LIMIT 1];
        System.assertEquals(testCustomer.Id, testSearch.Contact__c);
    }
    
    @isTest static void testGetGenderOptions(){
        // returned options should be male and female
        List<String> expectedGenderOptions = new List<String>();
        expectedGenderOptions.add('Male');
        expectedGenderOptions.add('Female');
        List<String> actualGenderOptions = CustomerSearchRequestPageController.getGenderOptions();
        System.assertEquals(expectedGenderOptions, actualGenderOptions);
    }
    
    @isTest static void testGetSpecializationOptions(){
        // returned options should be Cardiologist, Chiropractor, General Practitioner, Oncologist,	OBGYN,
        // and Proctologist
        List<String> expectedSpecializationOptions = new List<String>();
        expectedSpecializationOptions.add('Cardiologist');
        expectedSpecializationOptions.add('Chiropractor');
        expectedSpecializationOptions.add('General Practitioner');
        expectedSpecializationOptions.add('Oncologist');
        expectedSpecializationOptions.add('OBGYN');
        expectedSpecializationOptions.add('Proctologist');
        List<String> actualSpecializationOptions = 
            CustomerSearchRequestPageController.getSpecializationOptions();
        System.assertEquals(expectedSpecializationOptions, actualSpecializationOptions);
    }
    
    @isTest static void testGetLanguageOptions(){
        // returned options should be English, Spanish, French, and Chinese
        List<String> expectedLanguageOptions = new List<String>();
        expectedLanguageOptions.add('English');
        expectedLanguageOptions.add('Spanish');
        expectedLanguageOptions.add('French');
        expectedLanguageOptions.add('Chinese');
        List<String> actualLanguageOptions = CustomerSearchRequestPageController.getLanguageOptions();
        System.assertEquals(expectedLanguageOptions, actualLanguageOptions);
    }
    
    @isTest static void testGetDoctorLanguages(){
        // returned languages should be English and Spanish
        UtilityTestClass.testFactory();
        List<String> expectedLanguages = new List<String>();
        expectedLanguages.add('English');
        expectedLanguages.add('Spanish');
        Contact testDoctor = [SELECT Id FROM Contact WHERE LastName='Doctor' LIMIT 1];
        List<string> actualLanguages = CustomerSearchRequestPageController.getDoctorLanguages(testDoctor.Id);
        System.assertEquals(expectedLanguages, actualLanguages);
    }
}