babbageprod/force-app/main/default/objects/Contact/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexes</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Specialties</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <label>Doctor</label>
</RecordType>

babbageprod/force-app/main/default/objects/Residence__c/Residence__c.object-meta.xml
<CustomObject>
    <label>Residence</label>
    <nameField>
        <label>Residence Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Search__c/Search__c.object-meta.xml
<CustomObject>
    <label>Search</label>
    <nameField>
        <displayFormat>Search-{00000}</displayFormat>
        <label>Search Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Searches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

babbageprod/force-app/main/default/objects/Search__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Languages</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Search__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexes</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/objects/Search__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Specialties</valueSetName>
    </valueSet>
</CustomField>

babbageprod/force-app/main/default/globalValueSets/Languages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>English</fullName>
        <default>true</default>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>Spanish</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese</fullName>
    </customValue>
    <masterLabel>Languages</masterLabel>
</GlobalValueSet>

babbageprod/force-app/main/default/globalValueSets/Sexes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Male</fullName>
    </customValue>
    <customValue>
        <fullName>Female</fullName>
    </customValue>
    <masterLabel>Sexes</masterLabel>
</GlobalValueSet>

babbageprod/force-app/main/default/globalValueSets/Specialties.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cardiologist</fullName>
    </customValue>
    <customValue>
        <fullName>Chiropractor</fullName>
    </customValue>
    <customValue>
        <fullName>General Practitioner</fullName>
    </customValue>
    <customValue>
        <fullName>Oncologist</fullName>
    </customValue>
    <customValue>
        <fullName>OBGYN</fullName>
    </customValue>
    <customValue>
        <fullName>Proctologist</fullName>
    </customValue>
    <masterLabel>Specialties</masterLabel>
</GlobalValueSet>

babbageprod/force-app/main/default/classes/CustomerSearchRequestPageController.cls
public without sharing class CustomerSearchRequestPageController {
    // function to return matching doctors based on soql query
    @AuraEnabled
    public static List<Residence__c> returnMatchingDoctors(string searchquery){
        List<Residence__c> matchingDoctors = Database.query(searchquery);  
        return matchingDoctors;
    }
    
    // function to insert search record when user clicks 'Search' button on CustomerSearchPage
    @AuraEnabled
    public static void insertSearchRecord(Search__c searchToInsert){
        insert searchToInsert;
    }
    
    // function to return gender options for CustomerSearchPage
    @AuraEnabled
    public static List<String> getGenderOptions(){
        List<Schema.PicklistEntry> picklistValues = Contact.Sex__c.getDescribe().getPicklistValues();
        List<String> returnedOptions = new List<String>();
        for(Schema.PicklistEntry spe : picklistValues){
            returnedOptions.add(spe.getValue());
        }
        return returnedOptions;
    }
    
    // function to return specialization options for CustomerSearchPage
    @AuraEnabled
    public static List<String> getSpecializationOptions(){
        List<Schema.PicklistEntry> picklistValues = 
            Contact.Specialization__c.getDescribe().getPicklistValues();
        List<String> returnedOptions = new List<String>();
        for(Schema.PicklistEntry spe : picklistValues){
            returnedOptions.add(spe.getValue());
        }
        return returnedOptions;
    }
    
    // function to return language options for CustomerSearchPage
    @AuraEnabled
    public static List<String> getLanguageOptions(){
        List<Schema.PicklistEntry> picklistValues = 
            Contact.Language__c.getDescribe().getPicklistValues();
        List<String> returnedOptions = new List<String>();
        for(Schema.PicklistEntry spe : picklistValues){
            returnedOptions.add(spe.getValue());
        }
        return returnedOptions;
    }
    
    // function to return language options for CustomerRequestPage
    @AuraEnabled
    public static List<String> getDoctorLanguages(String doctorId){
        Contact doctor = [SELECT Id, Language__c FROM Contact WHERE Id=:doctorId LIMIT 1];
        return doctor.Language__c.split(';');
    }
    
    // function to get id of contact associated with current community user to allow insertion of search
    // and appointment records
    @AuraEnabled
    public static Id getContactId(){
        id userId = UserInfo.getUserId();
		User u = [select id, contactId from User where id = : userId];
		id getContactId = u.contactId;
		return getContactId;
    }
}